### ISSUE TITLE
Recent changes that caused metrics collection to fail

### ISSUE THREAD

**Issue by yechuan51** [knative-extensions/monitoring#23]
Hi, I believe a recent PR: https://github.com/knative-extensions/monitoring/pull/21 have caused the prometheus metrics collection to fail. 

I was following the instruction on https://knative.dev/docs/eventing/observability/metrics/collecting-metrics/ but then I realized that the knative metrics do not appear on the dashboard. After hours of debugging, I noticed that the service monitors have configured their port to "metrics", but the actual services(i.e. activator), exposes their metrics on a port with "http-metrics". 

I was able to get the metrics collected by manually patching the monitor with the correct port. 

@zchenyu

**Comment by dprotaso** [comment]
@yechuan51 looks like you're right - the Service has port names `http-metrics` but the deployment has `metrics`

Can you open a new PR with the fixes?

**Comment by yechuan51** [comment]
Done, PTAL https://github.com/knative-extensions/monitoring/pull/24

**Comment by dprotaso** [comment]
Thanks!

**Comment by zchenyu** [comment]
Huh my memory is a bit foggy on this, but IIRC the reason I filed that PR was because port http-metrics wasn't working for me (was a fresh knative serving installation)

**Comment by dprotaso** [comment]
Hey @zchenyu can you confirm the new changes- I'm included to think the ServiceMonitor would use the port names on the K8s Service. Though I'm not an expert here :)

**Comment by zchenyu** [comment]
Ah I think I know what's wrong. I was using PodMonitoring instead of ServiceMonitor as per https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#gmp-pod-monitoring
That references monitors the pod's (i.e. the deployment) port names.

I didn't even notice that the service and deployment port names were different.
